### ISSUE TITLE
aarch64 cross build

### ISSUE THREAD

**Issue by alucryd** [TerraMasterOfficial/app-pkg-tools#1]
I see the `makeapp_arm` binary is an aarch64 binary. Previously it was possible to build aarch64 packages with a single x86_64 `makeapp` binary for TOS 4. Can we still do the same with TOS5? Building aarch64 packages with the `makeapp_x64` binary?

**Comment by TerraMasterOfficial** [comment]
> I see the `makeapp_arm` binary is an aarch64 binary. Previously it was possible to build aarch64 packages with a single x86_64 `makeapp` binary for TOS 4. Can we still do the same with TOS5? Building aarch64 packages with the `makeapp_x64` binary?

Yes, you can use makeapp_x64 for package aarch64 app on amd64 platform.

**Comment by alucryd** [comment]
Great, thanks for the reply!
